export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const ADD_NEW_TASK_SUCCESS = 'ADD_NEW_TASK_SUCCESS';
export const ADD_NEW_TASK_FAILED = 'ADD_NEW_TASK_FAILED';
export const TOGGLE_ONE_TASK = 'TOGGLE_ONE_TASK';
export const TOGGLE_ONE_TASK_SUCCESS = 'TOGGLE_ONE_TASK_SUCCESS';
export const TOGGLE_ONE_TASK_FAILED = 'TOGGLE_ONE_TASK_FAILED';
